import { useState, useEffect } from 'react'
import { TrendingUp, BarChart3, AlertCircle, Brain, Sparkles } from 'lucide-react'
import { generateDrugEfficacyForecast, isAIEnabled } from '../services/aiForecasting'

const DrugForecastPanel = ({ drugData }) => {
  const [forecast, setForecast] = useState(null)
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    loadForecast()
  }, [drugData.drugName])

  const loadForecast = async () => {
    setLoading(true)
    try {
      const result = await generateDrugEfficacyForecast(drugData)
      setForecast(result)
    } catch (err) {
      console.error(err)
    } finally {
      setLoading(false)
    }
  }

  if (loading) {
    return (
      <div className="card">
        <div className="flex items-center justify-center py-12">
          <div className="text-center">
            <Brain className="w-12 h-12 text-slate-600 animate-pulse mx-auto mb-4" />
            <p className="text-slate-600 font-medium">Analyzing drug efficacy data...</p>
          </div>
        </div>
      </div>
    )
  }

  if (!forecast) return null

  return (
    <div className="card bg-slate-50 border-slate-300">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center space-x-3">
          <div className="bg-slate-700 p-2.5 rounded-lg">
            <Sparkles className="w-6 h-6 text-white" />
          </div>
          <div>
            <h3 className="text-xl font-bold text-slate-900">AI Drug Efficacy Forecast</h3>
            <p className="text-sm text-slate-600">
              {isAIEnabled() ? 'Generated by GPT-4 Turbo' : 'Simulated AI Analysis'}
            </p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <span className="inline-flex items-center px-3 py-1 rounded-lg text-xs font-semibold bg-slate-200 text-slate-700 border border-slate-300">
            <Brain className="w-3 h-3 mr-1" />
            AI Forecast
          </span>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-6 mb-6">
        <div className="bg-white rounded-xl p-6 border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm font-semibold text-slate-600 uppercase tracking-wide">3-Year Prediction</span>
            <TrendingUp className="w-5 h-5 text-slate-600" />
          </div>
          <div className="text-3xl font-bold text-slate-900 mb-2">
            {forecast.threeYearPrediction.toFixed(1)}%
          </div>
          <p className="text-xs text-slate-500">Projected response rate</p>
        </div>

        <div className="bg-white rounded-xl p-6 border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm font-semibold text-slate-600 uppercase tracking-wide">5-Year Prediction</span>
            <BarChart3 className="w-5 h-5 text-slate-600" />
          </div>
          <div className="text-3xl font-bold text-slate-900 mb-2">
            {forecast.fiveYearPrediction.toFixed(1)}%
          </div>
          <p className="text-xs text-slate-500">Long-term efficacy</p>
        </div>

        <div className="bg-white rounded-xl p-6 border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm font-semibold text-slate-600 uppercase tracking-wide">Trend Analysis</span>
            <AlertCircle className="w-5 h-5 text-slate-600" />
          </div>
          <div className="text-2xl font-bold text-slate-900 mb-2">
            {forecast.trendAnalysis}
          </div>
          <p className="text-xs text-slate-500">Efficacy trajectory</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-6 mb-6">
        <div className="bg-white rounded-xl p-6 border border-slate-200">
          <h4 className="text-sm font-bold text-slate-900 mb-4 uppercase tracking-wide">
            Confidence Interval
          </h4>
          <div className="space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-sm text-slate-600">Lower Bound</span>
              <span className="text-lg font-bold text-slate-900">{forecast.confidenceInterval.lower.toFixed(1)}%</span>
            </div>
            <div className="w-full bg-slate-200 rounded-full h-2">
              <div 
                className="bg-slate-600 h-2 rounded-full" 
                style={{ width: `${forecast.confidenceInterval.lower}%` }}
              />
            </div>
            <div className="flex justify-between items-center">
              <span className="text-sm text-slate-600">Upper Bound</span>
              <span className="text-lg font-bold text-slate-900">{forecast.confidenceInterval.upper.toFixed(1)}%</span>
            </div>
            <div className="w-full bg-slate-200 rounded-full h-2">
              <div 
                className="bg-slate-700 h-2 rounded-full" 
                style={{ width: `${forecast.confidenceInterval.upper}%` }}
              />
            </div>
          </div>
        </div>

        <div className="bg-white rounded-xl p-6 border border-slate-200">
          <h4 className="text-sm font-bold text-slate-900 mb-4 uppercase tracking-wide">
            Market Projection
          </h4>
          <p className="text-sm text-slate-700 leading-relaxed">
            {forecast.marketProjection}
          </p>
        </div>
      </div>

      <div className="bg-white rounded-xl p-6 border border-slate-200">
        <h4 className="text-sm font-bold text-slate-900 mb-4 uppercase tracking-wide flex items-center">
          <Brain className="w-4 h-4 mr-2 text-slate-600" />
          Key Insights
        </h4>
        <ul className="space-y-3">
          {forecast.keyInsights.map((insight, index) => (
            <li key={index} className="flex items-start space-x-3">
              <div className="bg-slate-200 rounded-full p-1 mt-0.5">
                <div className="w-2 h-2 bg-slate-600 rounded-full" />
              </div>
              <span className="text-sm text-slate-700 leading-relaxed">{insight}</span>
            </li>
          ))}
        </ul>
      </div>

      <div className="mt-6 bg-slate-100 border border-slate-300 rounded-xl p-4">
        <p className="text-xs text-slate-700 leading-relaxed">
          <strong>Note:</strong> This forecast is generated using {isAIEnabled() ? 'OpenAI GPT-4 Turbo' : 'statistical modeling'} based on historical response rates, temporal trends, and patient enrollment data. 
          Predictions should be validated with ongoing clinical trial results.
        </p>
      </div>
    </div>
  )
}

export default DrugForecastPanel
